### PR TITLE
Fix Toeplitz SVD

### LINKED ISSUE #25: New mass-like noise handling can use Mahalanobis distance
[TSVD code](https://github.com/usnistgov/Pope.jl/blob/cabaa1f324ddd4c5c072d45f4f3a68d9de5d9e1f/src/basis_creation.jl#L106) has the note
```
    # The RIGHT thing to do would be to whiten residual before taking the TSVD.
    # However, Julia 0.6 doesn't support fast Toeplitz factors, and we are calling this
    # function because we don't trust the ARMA models. So let us work instead with the Euclidean residual.
```

We should fix this. Package [ToeplitzMatrices](https://github.com/JuliaMatrices/ToeplitzMatrices.jl/) can help.

### PR DESCRIPTION
**Pull request by joefowler**
Fixes #25: use Mahalanobis distance when doing SVD on residuals in the new (autocorrelation vector) basis analysis.

### CODE REVIEW

File: test/basis_creation.jl [hunk 1]
```diff
@@ -72,10 +72,10 @@ mass3_basis, mass3_basisinfo = Pope.create_basis_one_channel(data,noise_result,
...
 
 @testset "scripts with SVDBasis" begin
-    @test success(run(`../scripts/noise_analysis.jl $noisepath -o $noise_result_path`))
-    @test success(run(`../scripts/basis_create.jl $ljhpath $noise_result_path -o $model_path`))
+    @test success(run(`julia ../scripts/noise_analysis.jl $noisepath -o $noise_result_path`))
+    @test success(run(`julia ../scripts/basis_create.jl $ljhpath $noise_result_path -o $model_path`))
     if !haskey(ENV,"POPE_NOMATPLOTLIB")
-        @test success(run(`../scripts/basis_plots.jl $model_path`))
-        @test success(run(`../scripts/noise_plots.jl $noise_result_path`))
+        @test success(run(`julia ../scripts/basis_plots.jl $model_path`))
```
Comment (ggggggggg) [inline test/basis_creation.jl]: why are some `julia script.jl` and some `./script.jl`?

Comment (joefowler) [reply test/basis_creation.jl]: They aren't supposed to be mixed like that.

Anyway, I cannot get my Travis test to work with `using Pkg`. Why not????
